DIMENSION_MAX = 50
DIMENSION_MIN = 10
DIMENSION_DEFAULT = 25

ROOM_COUNT_DEFAULT = 5
ROOM_DIMENSION_DEFAULT = 10
ROOM_DIMENSION_MIN = 4

# Tile Types
WALL = 1
FLOOR = 0

DUNGEON_FILE_DEFAULT = 'dungeon.xlsx'
DUNGEON_DIRECTORY = 'dungeons/'